/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ScrollSystem;

import ScrollSystem.FileHandlers.Database;

import java.util.*;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        //initialise database
        String dbFilepath = "src/main/java/ScrollSystem/resources/FileHandlers/database.db";
        Database database = new Database(dbFilepath);
    }

}
